import { toCamelCase, toPascalCase, propertyKey } from './naming';
import { OursBundle } from 'src/bundle';
import { JsonSchema, JsonSchemaType } from 'src/resources';
import { splitRef } from 'src/validate';

/**
 * Emit one TypeScript module containing a Zod schema and inferred type for
 * every model in the bundle, every shared `$defs` entry, and a const tuple
 * for every inline vocabulary.
 *
 * Output is deterministic: declarations are sorted by name and then
 * topologically ordered so each schema is declared before it is used.
 */
export function emitZodModule(bundle: OursBundle): string {
  const ctx = new EmitContext(bundle);
  const declarations = ctx.collectDeclarations();
  const ordered = topologicalOrder(declarations, (d) =>
    ctx.dependenciesOf(d.schema, d.doc),
  );

  const lines: string[] = [];
  lines.push(
    '// ~~ Generated by @opendnd/ours from an OURS bundle. Do not edit by hand. ~~',
    `// Ontology: ${bundle.ontology.url} (version ${bundle.ontology.version})`,
    '',
    "import { z } from 'zod';",
    '',
  );

  const vocabularies = [...bundle.vocabularies.values()]
    .filter((v) => v.codes && v.codes.length > 0)
    .sort((a, b) => a.id.localeCompare(b.id));
  for (const vocabulary of vocabularies) {
    const name = toCamelCase(vocabulary.id);
    lines.push(
      `/** ${vocabulary.name}: ${vocabulary.description ?? vocabulary.url} */`,
      `export const ${name}Codes = [`,
      ...vocabulary.codes!.map((c) => `  ${JSON.stringify(c.code)},`),
      '] as const;',
      `export const ${name}Schema = z.enum(${name}Codes);`,
      `export type ${toPascalCase(vocabulary.id)} = z.infer<typeof ${name}Schema>;`,
      '',
    );
  }

  for (const decl of ordered) {
    const pascal = toPascalCase(decl.name);
    const camel = toCamelCase(decl.name);
    const doc = decl.schema.description ?? decl.description;
    if (doc) lines.push(`/** ${doc.replace(/\*\//g, '* /')} */`);
    lines.push(
      `export const ${camel}Schema = ${ctx.emit(decl.schema, decl.doc, 0)};`,
      `export type ${pascal} = z.infer<typeof ${camel}Schema>;`,
      '',
    );
  }

  const models = [...bundle.models.values()].sort((a, b) =>
    a.id.localeCompare(b.id),
  );
  lines.push(
    '/** Every model in the ontology, keyed by model id. */',
    'export const models = {',
    ...models.map(
      (m) => `  ${propertyKey(m.id)}: ${toCamelCase(m.name)}Schema,`,
    ),
    '} as const;',
    'export type ModelId = keyof typeof models;',
    '',
  );

  return lines.join('\n');
}

interface Declaration {
  readonly name: string;
  readonly schema: JsonSchema;
  /** The `$id` of the document this schema lives in, for resolving `$ref`. */
  readonly doc: string;
  readonly description?: string;
}

class EmitContext {
  /** Maps "<doc>#<pointer>" to the declaration name it resolves to. */
  private readonly refNames = new Map<string, string>();

  constructor(private readonly bundle: OursBundle) {}

  collectDeclarations(): Declaration[] {
    const decls: Declaration[] = [];
    const docs = [...this.bundle.schemas.entries()].sort(([a], [b]) =>
      a.localeCompare(b),
    );
    for (const [id, schema] of docs) {
      for (const [defName, def] of Object.entries(schema.$defs ?? {}).sort(
        ([a], [b]) => a.localeCompare(b),
      )) {
        this.refNames.set(`${id}#/$defs/${defName}`, defName);
        decls.push({ name: defName, schema: def, doc: id });
      }
    }
    const models = [...this.bundle.models.values()].sort((a, b) =>
      a.id.localeCompare(b.id),
    );
    for (const model of models) {
      const schema = this.bundle.schemas.get(model.schema);
      if (!schema) throw new Error(`Model ${model.id}: schema not loaded`);
      this.refNames.set(`${model.schema}#`, model.name);
      this.refNames.set(`${model.schema}#/`, model.name);
      decls.push({
        name: model.name,
        schema,
        doc: model.schema,
        description: model.description,
      });
    }
    return decls;
  }

  dependenciesOf(schema: JsonSchema, doc: string): string[] {
    const deps = new Set<string>();
    const visit = (node: JsonSchema) => {
      if (node.$ref !== undefined) deps.add(this.refName(node.$ref, doc));
      // $defs are separate declarations; do not descend into them.
      for (const p of Object.values(node.properties ?? {})) visit(p);
      if (node.items) visit(node.items);
      if (typeof node.additionalProperties === 'object') {
        visit(node.additionalProperties);
      }
      for (const key of ['allOf', 'anyOf', 'oneOf'] as const) {
        (node[key] ?? []).forEach(visit);
      }
    };
    visit(schema);
    return [...deps];
  }

  emit(schema: JsonSchema, doc: string, indent: number): string {
    const pad = '  '.repeat(indent);
    const inner = '  '.repeat(indent + 1);

    if (schema.$ref !== undefined) {
      return `${toCamelCase(this.refName(schema.$ref, doc))}Schema`;
    }
    if (schema.allOf) {
      return this.emitAllOf(schema, doc, indent);
    }
    if (schema.oneOf || schema.anyOf) {
      const parts = (schema.oneOf ?? schema.anyOf)!;
      return `z.union([\n${parts
        .map((p) => `${inner}${this.emit(p, doc, indent + 1)},`)
        .join('\n')}\n${pad}])`;
    }
    if (schema.const !== undefined) {
      return `z.literal(${JSON.stringify(schema.const)})`;
    }
    const vocab = schema['x-ours-vocabulary'];
    if (vocab !== undefined) {
      const v = this.bundle.vocabularies.get(vocab);
      if (!v) throw new Error(`Unknown vocabulary ${vocab}`);
      return this.withDefault(`${toCamelCase(v.id)}Schema`, schema);
    }
    if (schema.enum) {
      const allStrings = schema.enum.every((e) => typeof e === 'string');
      if (allStrings) {
        return this.withDefault(
          `z.enum([${schema.enum.map((e) => JSON.stringify(e)).join(', ')}])`,
          schema,
        );
      }
      return `z.union([${schema.enum
        .map((e) => `z.literal(${JSON.stringify(e)})`)
        .join(', ')}])`;
    }

    const types = normaliseTypes(schema);
    const nullable = types.includes('null');
    const concrete = types.filter((t) => t !== 'null');
    let expr: string;
    if (concrete.length === 0) {
      expr = nullable ? 'z.null()' : 'z.unknown()';
      return expr;
    } else if (concrete.length === 1) {
      expr = this.emitSingle(concrete[0], schema, doc, indent);
    } else {
      expr = `z.union([${concrete
        .map((t) => this.emitSingle(t, schema, doc, indent))
        .join(', ')}])`;
    }
    if (nullable) expr += '.nullable()';
    return this.withDefault(expr, schema);
  }

  private emitSingle(
    type: JsonSchemaType,
    schema: JsonSchema,
    doc: string,
    indent: number,
  ): string {
    switch (type) {
      case 'string':
        return emitString(schema);
      case 'integer': {
        let e = 'z.int()';
        if (schema.minimum !== undefined) e += `.min(${schema.minimum})`;
        if (schema.maximum !== undefined) e += `.max(${schema.maximum})`;
        return e;
      }
      case 'number': {
        let e = 'z.number()';
        if (schema.minimum !== undefined) e += `.min(${schema.minimum})`;
        if (schema.maximum !== undefined) e += `.max(${schema.maximum})`;
        return e;
      }
      case 'boolean':
        return 'z.boolean()';
      case 'null':
        return 'z.null()';
      case 'array': {
        const items = schema.items
          ? this.emit(schema.items, doc, indent)
          : 'z.unknown()';
        let e = `z.array(${items})`;
        if (schema.minItems !== undefined) e += `.min(${schema.minItems})`;
        if (schema.maxItems !== undefined) e += `.max(${schema.maxItems})`;
        return e;
      }
      case 'object':
        return this.emitObject(schema, doc, indent);
      default:
        throw new Error(`Unsupported JSON Schema type ${String(type)}`);
    }
  }

  private emitObject(schema: JsonSchema, doc: string, indent: number): string {
    const pad = '  '.repeat(indent);
    const inner = '  '.repeat(indent + 1);
    const props = Object.entries(schema.properties ?? {});
    if (props.length === 0) {
      if (typeof schema.additionalProperties === 'object') {
        return `z.record(z.string(), ${this.emit(schema.additionalProperties, doc, indent)})`;
      }
      return schema.additionalProperties === false
        ? 'z.strictObject({})'
        : 'z.record(z.string(), z.unknown())';
    }
    const required = new Set(schema.required ?? []);
    const fields = props.map(([name, prop]) => {
      let e = this.emit(prop, doc, indent + 1);
      if (!required.has(name) && prop.default === undefined) e += '.optional()';
      const comment = prop.description
        ? `${inner}/** ${prop.description} */\n`
        : '';
      return `${comment}${inner}${propertyKey(name)}: ${e},`;
    });
    const ctor =
      schema.additionalProperties === false ? 'z.strictObject' : 'z.object';
    return `${ctor}({\n${fields.join('\n')}\n${pad}})`;
  }

  /**
   * `allOf` is used for "extends": flatten object members into one object.
   * Every part must resolve to an object schema (directly or via `$ref`).
   */
  private emitAllOf(schema: JsonSchema, doc: string, indent: number): string {
    const merged: JsonSchema = {
      type: 'object',
      properties: {},
      required: [],
      additionalProperties: schema.additionalProperties,
      description: schema.description,
    };
    const parts = [...schema.allOf!];
    if (schema.properties) {
      parts.push({
        type: 'object',
        properties: schema.properties,
        required: schema.required,
      });
    }
    for (const part of parts) {
      const resolved = this.resolveObject(part, doc);
      // Properties pulled in from another document keep resolving against
      // that document: rewrite their local `#/...` refs to absolute ones.
      const props = rehomeRefs(resolved.schema.properties ?? {}, resolved.doc);
      Object.assign(merged.properties!, props);
      merged.required!.push(...(resolved.schema.required ?? []));
      if (resolved.schema.additionalProperties === false) {
        merged.additionalProperties = false;
      }
    }
    return this.emitObject(merged, doc, indent);
  }

  private resolveObject(
    part: JsonSchema,
    doc: string,
  ): { schema: JsonSchema; doc: string } {
    if (part.$ref === undefined) return { schema: part, doc };
    const { doc: targetDoc, pointer } = splitRef(part.$ref, doc);
    const target = this.bundle.schemas.get(targetDoc);
    if (!target) throw new Error(`$ref ${part.$ref} does not resolve`);
    if (pointer === '' || pointer === '/') {
      return { schema: target, doc: targetDoc };
    }
    const m = /^\/\$defs\/([^/]+)$/.exec(pointer);
    const def = m && target.$defs?.[m[1]];
    if (!def) throw new Error(`$ref ${part.$ref} does not resolve`);
    return this.resolveObject(def, targetDoc);
  }

  private refName(ref: string, doc: string): string {
    const { doc: targetDoc, pointer } = splitRef(ref, doc);
    const key = `${targetDoc}#${pointer}`;
    const name = this.refNames.get(key);
    if (!name) throw new Error(`$ref ${ref} (from ${doc}) has no declaration`);
    return name;
  }

  private withDefault(expr: string, schema: JsonSchema): string {
    return schema.default === undefined
      ? expr
      : `${expr}.default(${JSON.stringify(schema.default)})`;
  }
}

/** Deep-copy `schemas`, turning `#/...` refs into `<doc>#/...` refs. */
function rehomeRefs<T extends Record<string, JsonSchema>>(
  schemas: T,
  doc: string,
): T {
  const out: Record<string, JsonSchema> = {};
  for (const [k, v] of Object.entries(schemas)) out[k] = rehome(v, doc);
  return out as T;
}

function rehome(schema: JsonSchema, doc: string): JsonSchema {
  const copy: JsonSchema = { ...schema };
  if (copy.$ref !== undefined && copy.$ref.startsWith('#')) {
    copy.$ref = `${doc}${copy.$ref}`;
  }
  if (copy.properties) copy.properties = rehomeRefs(copy.properties, doc);
  if (copy.items) copy.items = rehome(copy.items, doc);
  if (typeof copy.additionalProperties === 'object') {
    copy.additionalProperties = rehome(copy.additionalProperties, doc);
  }
  for (const key of ['allOf', 'anyOf', 'oneOf'] as const) {
    if (copy[key]) copy[key] = copy[key]!.map((s) => rehome(s, doc));
  }
  return copy;
}

function emitString(schema: JsonSchema): string {
  switch (schema.format) {
    case 'uuid':
      return 'z.uuid()';
    case 'uri':
    case 'url':
      return 'z.url()';
    case 'date-time':
      return 'z.iso.datetime()';
    case 'date':
      return 'z.iso.date()';
    default: {
      let e = 'z.string()';
      if (schema.minLength !== undefined) e += `.min(${schema.minLength})`;
      if (schema.maxLength !== undefined) e += `.max(${schema.maxLength})`;
      if (schema.pattern !== undefined) {
        e += `.regex(new RegExp(${JSON.stringify(schema.pattern)}))`;
      }
      return e;
    }
  }
}

function normaliseTypes(schema: JsonSchema): JsonSchemaType[] {
  if (Array.isArray(schema.type)) return schema.type;
  if (schema.type) return [schema.type];
  if (schema.properties || schema.additionalProperties !== undefined) {
    return ['object'];
  }
  if (schema.items) return ['array'];
  return [];
}

/** Stable topological order; input order (already sorted) breaks ties. */
function topologicalOrder(
  decls: Declaration[],
  deps: (d: Declaration) => string[],
): Declaration[] {
  const byName = new Map(decls.map((d) => [d.name, d]));
  const done = new Set<string>();
  const visiting = new Set<string>();
  const out: Declaration[] = [];
  const visit = (d: Declaration, chain: string[]) => {
    if (done.has(d.name)) return;
    if (visiting.has(d.name)) {
      throw new Error(
        `Recursive schema reference is not supported: ${[...chain, d.name].join(' -> ')}`,
      );
    }
    visiting.add(d.name);
    for (const dep of deps(d)) {
      const target = byName.get(dep);
      if (!target) throw new Error(`${d.name} depends on unknown ${dep}`);
      if (target !== d) visit(target, [...chain, d.name]);
    }
    visiting.delete(d.name);
    done.add(d.name);
    out.push(d);
  };
  for (const d of decls) visit(d, []);
  return out;
}
