import { toCamelCase, toPascalCase, propertyKey } from './naming';
import { OursBundle } from '../bundle';
import { JsonSchema, JsonSchemaType } from '../resources';
import { splitRef } from '../validate';

/**
 * Emit one TypeScript module containing a Zod schema and inferred type for
 * every model in the bundle, every shared `$defs` entry, and a const tuple
 * for every inline vocabulary.
 *
 * Output is deterministic: declarations are sorted by name and then
 * topologically ordered so each schema is declared before it is used.
 */
export function emitZodModule(bundle: OursBundle): string {
  const ctx = new EmitContext(bundle);
  const declarations = ctx.collectDeclarations();
  const ordered = topologicalOrder(declarations, (d) =>
    ctx.dependenciesOf(d.schema, d.doc),
  );

  const lines: string[] = [];
  lines.push(
    '// ~~ Generated by @opendnd/ours from an OURS bundle. Do not edit by hand. ~~',
    `// Ontology: ${bundle.ontology.url} (version ${bundle.ontology.version})`,
    '',
    "import { z } from 'zod';",
    '',
  );

  const vocabularies = [...bundle.vocabularies.values()]
    .filter((v) => v.codes && v.codes.length > 0)
    .sort((a, b) => a.id.localeCompare(b.id));
  for (const vocabulary of vocabularies) {
    const name = toCamelCase(vocabulary.id);
    lines.push(
      `/** ${vocabulary.name}: ${vocabulary.description ?? vocabulary.url} */`,
      `export const ${name}Codes = [`,
      ...vocabulary.codes!.map((c) => `  ${JSON.stringify(c.code)},`),
      '] as const;',
      `export const ${name}Schema = z.enum(${name}Codes);`,
      `export type ${toPascalCase(vocabulary.id)} = z.infer<typeof ${name}Schema>;`,
      '',
    );
  }

  for (const decl of ordered) {
    const pascal = toPascalCase(decl.name);
    const camel = toCamelCase(decl.name);
    const doc = decl.schema.description ?? decl.description;
    if (doc) lines.push(`/** ${doc.replace(/\*\//g, '* /')} */`);
    const alternatives = decl.schema.anyOf;
    const selfReferential = ctx
      .dependenciesOf(decl.schema, decl.doc)
      .includes(decl.name);
    if (
      selfReferential &&
      alternatives &&
      isRequiredAlternatives(alternatives)
    ) {
      /*
       * A refinement on a schema that refers to itself leaves TypeScript
       * unable to infer its type, so the object is declared first, referring
       * to its own unrefined form, and the refinement is layered on the
       * exported name. The constraint therefore holds at the top level of a
       * value and not inside its nested occurrences; the JSON Schema states
       * it at every level.
       */
      const { anyOf: _alternatives, ...rest } = decl.schema;
      ctx.selfRaw = decl.name;
      lines.push(
        `const ${camel}RawSchema = ${ctx.emit(rest, decl.doc, 0)};`,
        `export const ${camel}Schema = ${camel}RawSchema${requireOneOf(alternatives)};`,
      );
      ctx.selfRaw = undefined;
    } else {
      lines.push(
        `export const ${camel}Schema = ${ctx.emit(decl.schema, decl.doc, 0)};`,
      );
    }
    lines.push(`export type ${pascal} = z.infer<typeof ${camel}Schema>;`, '');
    ctx.emitted.add(decl.name);
  }

  const models = [...bundle.models.values()].sort((a, b) =>
    a.id.localeCompare(b.id),
  );
  /*
   * The code lists with their display text.
   *
   * The Zod enums above are what validation needs; a form needs to show a
   * person "Very poor" rather than `very-poor`, and it should not have to
   * carry its own copy of the labels and let them drift from the ontology.
   */
  lines.push(
    '/** Every code list, with the display text for each code. */',
    'export const vocabularies = {',
    ...vocabularies.map((v) =>
      [
        `  ${propertyKey(v.id)}: {`,
        `    id: ${JSON.stringify(v.id)},`,
        `    name: ${JSON.stringify(v.name)},`,
        ...(v.description
          ? [`    description: ${JSON.stringify(v.description)},`]
          : []),
        '    codes: [',
        ...v.codes!.map(
          (c) =>
            `      { code: ${JSON.stringify(c.code)}, display: ${JSON.stringify(
              c.display ?? c.code,
            )} },`,
        ),
        '    ],',
        '  },',
      ].join('\n'),
    ),
    '} as const;',
    'export type VocabularyId = keyof typeof vocabularies;',
    '',
  );

  lines.push(
    '/** Every model in the ontology, keyed by model id. */',
    'export const models = {',
    ...models.map(
      (m) => `  ${propertyKey(m.id)}: ${toCamelCase(m.name)}Schema,`,
    ),
    '} as const;',
    'export type ModelId = keyof typeof models;',
    '',
  );

  /*
   * What the schemas say about the platform's part in a record: the fields
   * the server sets, and the properties a record's in-world valid time is
   * read from when it does not state one.
   */
  const readOnly = new Set<string>();
  const validTime: string[] = [];
  for (const model of models) {
    const schema = bundle.schemas.get(model.schema)!;
    for (const [name, prop] of Object.entries(
      ctx.topLevelProperties(schema, model.schema),
    )) {
      if (prop.readOnly) readOnly.add(name);
    }
    const fields = schema['x-ours-valid-time'];
    if (fields) {
      validTime.push(`  ${propertyKey(model.id)}: ${JSON.stringify(fields)},`);
    }
  }
  lines.push(
    '/** Fields the API sets itself. A request may omit them and cannot override them. */',
    `export const readOnlyFields = ${JSON.stringify([...readOnly].sort())} as const;`,
    '',
    "/** The properties a record's in-world valid time is derived from when it states none, by model. Dotted paths. */",
    'export const validTimeFields = {',
    ...validTime,
    '} as const satisfies Partial<Record<ModelId, { begin: string; end?: string }>>;',
    '',
  );

  return lines.join('\n');
}

interface Declaration {
  readonly name: string;
  readonly schema: JsonSchema;
  /** The `$id` of the document this schema lives in, for resolving `$ref`. */
  readonly doc: string;
  readonly description?: string;
}

class EmitContext {
  /** Declarations already written, so a reference to anything else is deferred. */
  readonly emitted = new Set<string>();
  /** The declaration being emitted in two steps, whose self-references use the raw form. */
  selfRaw: string | undefined;
  /** Maps "<doc>#<pointer>" to the declaration name it resolves to. */
  private readonly refNames = new Map<string, string>();

  constructor(private readonly bundle: OursBundle) {}

  collectDeclarations(): Declaration[] {
    const decls: Declaration[] = [];
    const docs = [...this.bundle.schemas.entries()].sort(([a], [b]) =>
      a.localeCompare(b),
    );
    for (const [id, schema] of docs) {
      for (const [defName, def] of Object.entries(schema.$defs ?? {}).sort(
        ([a], [b]) => a.localeCompare(b),
      )) {
        this.refNames.set(`${id}#/$defs/${defName}`, defName);
        decls.push({ name: defName, schema: def, doc: id });
      }
    }
    const models = [...this.bundle.models.values()].sort((a, b) =>
      a.id.localeCompare(b.id),
    );
    for (const model of models) {
      const schema = this.bundle.schemas.get(model.schema);
      if (!schema) throw new Error(`Model ${model.id}: schema not loaded`);
      this.refNames.set(`${model.schema}#`, model.name);
      this.refNames.set(`${model.schema}#/`, model.name);
      decls.push({
        name: model.name,
        schema,
        doc: model.schema,
        description: model.description,
      });
    }
    return decls;
  }

  /** A model's properties, including those inherited through `allOf`. */
  topLevelProperties(
    schema: JsonSchema,
    doc: string,
  ): Record<string, JsonSchema> {
    const out: Record<string, JsonSchema> = {};
    for (const part of schema.allOf ?? []) {
      const resolved = this.resolveObject(part, doc);
      Object.assign(
        out,
        this.topLevelProperties(resolved.schema, resolved.doc),
      );
    }
    Object.assign(out, schema.properties ?? {});
    return out;
  }

  dependenciesOf(schema: JsonSchema, doc: string): string[] {
    const deps = new Set<string>();
    const visit = (node: JsonSchema) => {
      if (node.$ref !== undefined) deps.add(this.refName(node.$ref, doc));
      // $defs are separate declarations; do not descend into them.
      for (const p of Object.values(node.properties ?? {})) visit(p);
      if (node.items) visit(node.items);
      if (typeof node.additionalProperties === 'object') {
        visit(node.additionalProperties);
      }
      for (const key of ['allOf', 'anyOf', 'oneOf'] as const) {
        (node[key] ?? []).forEach(visit);
      }
    };
    visit(schema);
    return [...deps];
  }

  emit(schema: JsonSchema, doc: string, indent: number): string {
    const pad = '  '.repeat(indent);
    const inner = '  '.repeat(indent + 1);

    if (schema.$ref !== undefined) {
      const name = this.refName(schema.$ref, doc);
      const suffix = name === this.selfRaw ? 'RawSchema' : 'Schema';
      return `${toCamelCase(name)}${suffix}`;
    }
    if (schema.allOf) {
      return this.emitAllOf(schema, doc, indent);
    }
    if (schema.anyOf && isRequiredAlternatives(schema.anyOf)) {
      // `anyOf` made only of `required` lists says "at least one of these
      // sets of fields is present", which is a constraint on one object
      // rather than a choice between shapes, so it becomes a refinement.
      const { anyOf, ...rest } = schema;
      return `${this.emit(rest, doc, indent)}${requireOneOf(anyOf)}`;
    }
    if (schema.oneOf || schema.anyOf) {
      const parts = (schema.oneOf ?? schema.anyOf)!;
      return `z.union([\n${parts
        .map((p) => `${inner}${this.emit(p, doc, indent + 1)},`)
        .join('\n')}\n${pad}])`;
    }
    if (schema.const !== undefined) {
      return `z.literal(${JSON.stringify(schema.const)})`;
    }
    const vocab = schema['x-ours-vocabulary'];
    if (vocab !== undefined) {
      const v = this.bundle.vocabularies.get(vocab);
      if (!v) throw new Error(`Unknown vocabulary ${vocab}`);
      return this.withDefault(`${toCamelCase(v.id)}Schema`, schema);
    }
    if (schema.enum) {
      const allStrings = schema.enum.every((e) => typeof e === 'string');
      if (allStrings) {
        return this.withDefault(
          `z.enum([${schema.enum.map((e) => JSON.stringify(e)).join(', ')}])`,
          schema,
        );
      }
      return `z.union([${schema.enum
        .map((e) => `z.literal(${JSON.stringify(e)})`)
        .join(', ')}])`;
    }

    const types = normaliseTypes(schema);
    const nullable = types.includes('null');
    const concrete = types.filter((t) => t !== 'null');
    let expr: string;
    if (concrete.length === 0) {
      expr = nullable ? 'z.null()' : 'z.unknown()';
      return expr;
    } else if (concrete.length === 1) {
      expr = this.emitSingle(concrete[0], schema, doc, indent);
    } else {
      expr = `z.union([${concrete
        .map((t) => this.emitSingle(t, schema, doc, indent))
        .join(', ')}])`;
    }
    if (nullable) expr += '.nullable()';
    return this.withDefault(expr, schema);
  }

  private emitSingle(
    type: JsonSchemaType,
    schema: JsonSchema,
    doc: string,
    indent: number,
  ): string {
    switch (type) {
      case 'string':
        return emitString(schema);
      case 'integer': {
        let e = 'z.int()';
        if (schema.minimum !== undefined) e += `.min(${schema.minimum})`;
        if (schema.maximum !== undefined) e += `.max(${schema.maximum})`;
        return e;
      }
      case 'number': {
        let e = 'z.number()';
        if (schema.minimum !== undefined) e += `.min(${schema.minimum})`;
        if (schema.maximum !== undefined) e += `.max(${schema.maximum})`;
        return e;
      }
      case 'boolean':
        return 'z.boolean()';
      case 'null':
        return 'z.null()';
      case 'array': {
        const items = schema.items
          ? this.emit(schema.items, doc, indent)
          : 'z.unknown()';
        let e = `z.array(${items})`;
        if (schema.minItems !== undefined) e += `.min(${schema.minItems})`;
        if (schema.maxItems !== undefined) e += `.max(${schema.maxItems})`;
        return e;
      }
      case 'object':
        return this.emitObject(schema, doc, indent);
      default:
        throw new Error(`Unsupported JSON Schema type ${String(type)}`);
    }
  }

  private emitObject(schema: JsonSchema, doc: string, indent: number): string {
    const pad = '  '.repeat(indent);
    const inner = '  '.repeat(indent + 1);
    const props = Object.entries(schema.properties ?? {});
    if (props.length === 0) {
      if (typeof schema.additionalProperties === 'object') {
        return `z.record(z.string(), ${this.emit(schema.additionalProperties, doc, indent)})`;
      }
      return schema.additionalProperties === false
        ? 'z.strictObject({})'
        : 'z.record(z.string(), z.unknown())';
    }
    const required = new Set(schema.required ?? []);
    const fields = props.map(([name, prop]) => {
      let e = this.emit(prop, doc, indent + 1);
      if (!required.has(name) && prop.default === undefined) e += '.optional()';
      const comment = prop.description
        ? `${inner}/** ${prop.description} */\n`
        : '';
      /*
       * A property that refers to a schema not yet declared — the one being
       * declared, or another in a cycle with it — is emitted as a getter, which
       * is Zod's idiom for recursion: the reference is not evaluated until the
       * schema is used, by which time the constant exists, and TypeScript can
       * still infer the type without an annotation.
       */
      const deferred = this.dependenciesOf(prop, doc).some(
        (dep) => !this.emitted.has(dep),
      );
      if (deferred) {
        return `${comment}${inner}get ${propertyKey(name)}() {\n${inner}  return ${e};\n${inner}},`;
      }
      return `${comment}${inner}${propertyKey(name)}: ${e},`;
    });
    const ctor = isClosed(schema) ? 'z.strictObject' : 'z.object';
    return `${ctor}({\n${fields.join('\n')}\n${pad}})`;
  }

  /**
   * `allOf` is used for "extends": flatten object members into one object.
   * Every part must resolve to an object schema (directly or via `$ref`).
   */
  private emitAllOf(schema: JsonSchema, doc: string, indent: number): string {
    const merged: JsonSchema = {
      type: 'object',
      properties: {},
      required: [],
      additionalProperties: isClosed(schema)
        ? false
        : schema.additionalProperties,
      description: schema.description,
    };
    const parts = [...schema.allOf!];
    if (schema.properties) {
      parts.push({
        type: 'object',
        properties: schema.properties,
        required: schema.required,
      });
    }
    for (const part of parts) {
      const resolved = this.resolveObject(part, doc);
      // Properties pulled in from another document keep resolving against
      // that document: rewrite their local `#/...` refs to absolute ones.
      const props = rehomeRefs(resolved.schema.properties ?? {}, resolved.doc);
      Object.assign(merged.properties!, props);
      merged.required!.push(...(resolved.schema.required ?? []));
      if (resolved.schema.additionalProperties === false) {
        merged.additionalProperties = false;
      }
    }
    return this.emitObject(merged, doc, indent);
  }

  private resolveObject(
    part: JsonSchema,
    doc: string,
  ): { schema: JsonSchema; doc: string } {
    if (part.$ref === undefined) return { schema: part, doc };
    const { doc: targetDoc, pointer } = splitRef(part.$ref, doc);
    const target = this.bundle.schemas.get(targetDoc);
    if (!target) throw new Error(`$ref ${part.$ref} does not resolve`);
    if (pointer === '' || pointer === '/') {
      return { schema: target, doc: targetDoc };
    }
    const m = /^\/\$defs\/([^/]+)$/.exec(pointer);
    const def = m && target.$defs?.[m[1]];
    if (!def) throw new Error(`$ref ${part.$ref} does not resolve`);
    return this.resolveObject(def, targetDoc);
  }

  private refName(ref: string, doc: string): string {
    const { doc: targetDoc, pointer } = splitRef(ref, doc);
    const key = `${targetDoc}#${pointer}`;
    const name = this.refNames.get(key);
    if (!name) throw new Error(`$ref ${ref} (from ${doc}) has no declaration`);
    return name;
  }

  private withDefault(expr: string, schema: JsonSchema): string {
    return schema.default === undefined
      ? expr
      : `${expr}.default(${JSON.stringify(schema.default)})`;
  }
}

/** Deep-copy `schemas`, turning `#/...` refs into `<doc>#/...` refs. */
function rehomeRefs<T extends Record<string, JsonSchema>>(
  schemas: T,
  doc: string,
): T {
  const out: Record<string, JsonSchema> = {};
  for (const [k, v] of Object.entries(schemas)) out[k] = rehome(v, doc);
  return out as T;
}

function rehome(schema: JsonSchema, doc: string): JsonSchema {
  const copy: JsonSchema = { ...schema };
  if (copy.$ref !== undefined && copy.$ref.startsWith('#')) {
    copy.$ref = `${doc}${copy.$ref}`;
  }
  if (copy.properties) copy.properties = rehomeRefs(copy.properties, doc);
  if (copy.items) copy.items = rehome(copy.items, doc);
  if (typeof copy.additionalProperties === 'object') {
    copy.additionalProperties = rehome(copy.additionalProperties, doc);
  }
  for (const key of ['allOf', 'anyOf', 'oneOf'] as const) {
    if (copy[key]) copy[key] = copy[key]!.map((s) => rehome(s, doc));
  }
  return copy;
}

/**
 * Whether a schema admits no properties beyond the ones it declares. Draft
 * 2020-12 says it with `unevaluatedProperties` when the schema extends another
 * through `allOf`, and with `additionalProperties` otherwise.
 */
function isClosed(schema: JsonSchema): boolean {
  return (
    schema.additionalProperties === false ||
    schema.unevaluatedProperties === false
  );
}

function isRequiredAlternatives(parts: JsonSchema[]): boolean {
  return (
    parts.length > 0 &&
    parts.every(
      (part) =>
        Object.keys(part).every((key) => key === 'required') &&
        (part.required?.length ?? 0) > 0,
    )
  );
}

function requireOneOf(alternatives: JsonSchema[]): string {
  const sets = alternatives.map((a) => a.required ?? []);
  const label = sets.map((set) => set.join(' and ')).join(', or ');
  return (
    `.refine((value) => ${JSON.stringify(sets)}.some((keys) => ` +
    `keys.every((key) => (value as Record<string, unknown>)[key] !== undefined)), ` +
    `{ error: ${JSON.stringify(`one of ${label} is required`)} })`
  );
}

function emitString(schema: JsonSchema): string {
  switch (schema.format) {
    case 'uuid':
      return 'z.uuid()';
    case 'uri':
    case 'url':
      return 'z.url()';
    case 'date-time':
      return 'z.iso.datetime()';
    case 'date':
      return 'z.iso.date()';
    default: {
      let e = 'z.string()';
      if (schema.minLength !== undefined) e += `.min(${schema.minLength})`;
      if (schema.maxLength !== undefined) e += `.max(${schema.maxLength})`;
      if (schema.pattern !== undefined) {
        e += `.regex(new RegExp(${JSON.stringify(schema.pattern)}))`;
      }
      return e;
    }
  }
}

function normaliseTypes(schema: JsonSchema): JsonSchemaType[] {
  if (Array.isArray(schema.type)) return schema.type;
  if (schema.type) return [schema.type];
  if (
    schema.properties ||
    schema.additionalProperties !== undefined ||
    schema.unevaluatedProperties !== undefined
  ) {
    return ['object'];
  }
  if (schema.items) return ['array'];
  return [];
}

/** Stable topological order; input order (already sorted) breaks ties. */
function topologicalOrder(
  decls: Declaration[],
  deps: (d: Declaration) => string[],
): Declaration[] {
  const byName = new Map(decls.map((d) => [d.name, d]));
  const done = new Set<string>();
  const visiting = new Set<string>();
  const out: Declaration[] = [];
  const visit = (d: Declaration, chain: string[]) => {
    if (done.has(d.name)) return;
    // A cycle is left where it is: the declaration reached first is emitted
    // first, and the reference back to it becomes a deferred property.
    if (visiting.has(d.name)) return;
    visiting.add(d.name);
    for (const dep of deps(d)) {
      const target = byName.get(dep);
      if (!target) throw new Error(`${d.name} depends on unknown ${dep}`);
      if (target !== d) visit(target, [...chain, d.name]);
    }
    visiting.delete(d.name);
    done.add(d.name);
    out.push(d);
  };
  for (const d of decls) visit(d, []);
  return out;
}
