import type { Industry, Prosperity, Resource, Terrain } from '@opendnd/types';

/**
 * Settlement tables, ported from the 2018 dominia generator, which drew on
 * S. John Ross's "Medieval Demographics Made Easy" for support values and
 * scales. Codes match the ontology vocabularies terrain, resource, industry and
 * prosperity, so generated places validate against them.
 */

/** The die rolled for how many resource picks a terrain gets, and its candidates. */
export const TERRAIN_RESOURCES: Record<
  Terrain,
  { dice: string; resources: Resource[] }
> = {
  coastal: {
    dice: 'd6',
    resources: [
      'bananas',
      'cinnamon',
      'citrus',
      'cloves',
      'cocoa',
      'coffee',
      'cosmetics',
      'cotton',
      'crabs',
      'diamonds',
      'dyes',
      'fish',
      'incense',
      'jade',
      'marble',
      'obsidian',
      'pearls',
      'perfume',
      'salt',
      'silk',
      'spices',
      'sugar',
      'sulphur',
      'tea',
      'tobacco',
      'truffles',
      'whales',
    ],
  },
  desert: {
    dice: 'd2',
    resources: [
      'amber',
      'bronze',
      'camels',
      'clay',
      'goats',
      'gypsum',
      'incense',
      'iron',
      'salt',
      'spices',
    ],
  },
  grassland: {
    dice: 'd8',
    resources: [
      'aluminum',
      'amber',
      'bronze',
      'cattle',
      'chickens',
      'cinnamon',
      'citrus',
      'clay',
      'cloves',
      'coal',
      'cobalt',
      'cocoa',
      'coffee',
      'copper',
      'cosmetics',
      'cotton',
      'deer',
      'diamonds',
      'ducks',
      'dyes',
      'furs',
      'geese',
      'goats',
      'gold',
      'gypsum',
      'horses',
      'incense',
      'iron',
      'ivory',
      'jade',
      'marble',
      'mercury',
      'obsidian',
      'peacocks',
      'perfume',
      'pigs',
      'platinum',
      'rice',
      'salt',
      'sheep',
      'silk',
      'silver',
      'spices',
      'stone',
      'sugar',
      'sulphur',
      'tea',
      'tobacco',
      'truffles',
      'wheat',
      'wine',
      'wood',
      'wool',
      'honey',
    ],
  },
  hills: {
    dice: 'd6',
    resources: [
      'aluminum',
      'amber',
      'bronze',
      'cattle',
      'chickens',
      'clay',
      'coal',
      'cobalt',
      'copper',
      'deer',
      'diamonds',
      'ducks',
      'dyes',
      'furs',
      'geese',
      'goats',
      'gold',
      'gypsum',
      'horses',
      'incense',
      'iron',
      'ivory',
      'jade',
      'marble',
      'mercury',
      'obsidian',
      'peacocks',
      'perfume',
      'pigs',
      'platinum',
      'rice',
      'salt',
      'sheep',
      'silk',
      'silver',
      'spices',
      'stone',
      'sugar',
      'sulphur',
      'tea',
      'tobacco',
      'truffles',
      'wheat',
      'wine',
      'wood',
      'wool',
      'honey',
    ],
  },
  mountains: {
    dice: 'd4',
    resources: [
      'aluminum',
      'amber',
      'bronze',
      'clay',
      'coal',
      'cobalt',
      'copper',
      'diamonds',
      'dyes',
      'goats',
      'gold',
      'gypsum',
      'iron',
      'jade',
      'marble',
      'mercury',
      'obsidian',
      'platinum',
      'salt',
      'sheep',
      'silver',
      'stone',
      'sulphur',
      'wood',
      'wool',
    ],
  },
  plains: {
    dice: 'd6',
    resources: [
      'amber',
      'cattle',
      'chickens',
      'cinnamon',
      'citrus',
      'clay',
      'cloves',
      'cocoa',
      'coffee',
      'copper',
      'cosmetics',
      'cotton',
      'deer',
      'diamonds',
      'ducks',
      'dyes',
      'furs',
      'geese',
      'goats',
      'horses',
      'incense',
      'ivory',
      'peacocks',
      'perfume',
      'pigs',
      'rice',
      'sheep',
      'silk',
      'spices',
      'sugar',
      'tea',
      'tobacco',
      'truffles',
      'wheat',
      'wine',
      'wool',
      'honey',
    ],
  },
  snow: {
    dice: 'd2',
    resources: [
      'amber',
      'bronze',
      'coal',
      'cobalt',
      'copper',
      'deer',
      'furs',
      'gold',
      'gypsum',
      'iron',
      'jade',
      'marble',
      'mercury',
      'obsidian',
      'platinum',
      'salt',
      'sheep',
      'silver',
      'stone',
      'sulphur',
      'wool',
    ],
  },
  tundra: {
    dice: 'd4',
    resources: [
      'amber',
      'bronze',
      'coal',
      'cobalt',
      'copper',
      'deer',
      'furs',
      'gold',
      'gypsum',
      'iron',
      'jade',
      'marble',
      'mercury',
      'obsidian',
      'platinum',
      'salt',
      'sheep',
      'silver',
      'stone',
      'sulphur',
      'wool',
    ],
  },
  forest: {
    dice: 'd6',
    resources: [
      'aluminum',
      'amber',
      'bronze',
      'cinnamon',
      'citrus',
      'cloves',
      'coal',
      'cobalt',
      'cocoa',
      'copper',
      'deer',
      'diamonds',
      'dyes',
      'furs',
      'gold',
      'gypsum',
      'horses',
      'incense',
      'iron',
      'ivory',
      'jade',
      'marble',
      'mercury',
      'obsidian',
      'peacocks',
      'perfume',
      'pigs',
      'platinum',
      'salt',
      'silk',
      'silver',
      'spices',
      'stone',
      'sulphur',
      'truffles',
      'wood',
      'honey',
    ],
  },
  river: {
    dice: 'd6',
    resources: [
      'aluminum',
      'amber',
      'bronze',
      'cattle',
      'cinnamon',
      'citrus',
      'clay',
      'cloves',
      'coal',
      'cobalt',
      'cocoa',
      'coffee',
      'copper',
      'cosmetics',
      'cotton',
      'crabs',
      'deer',
      'diamonds',
      'ducks',
      'dyes',
      'fish',
      'furs',
      'geese',
      'gold',
      'gypsum',
      'horses',
      'incense',
      'iron',
      'ivory',
      'jade',
      'marble',
      'mercury',
      'obsidian',
      'peacocks',
      'perfume',
      'platinum',
      'rice',
      'salt',
      'silk',
      'silver',
      'spices',
      'stone',
      'sugar',
      'sulphur',
      'tea',
      'tobacco',
      'truffles',
      'wheat',
      'wine',
    ],
  },
  jungle: {
    dice: 'd4',
    resources: [
      'aluminum',
      'amber',
      'bananas',
      'bronze',
      'cinnamon',
      'citrus',
      'cloves',
      'coal',
      'cobalt',
      'cocoa',
      'copper',
      'deer',
      'diamonds',
      'dyes',
      'furs',
      'gold',
      'gypsum',
      'horses',
      'incense',
      'iron',
      'ivory',
      'jade',
      'marble',
      'mercury',
      'obsidian',
      'peacocks',
      'perfume',
      'pigs',
      'platinum',
      'salt',
      'silk',
      'silver',
      'spices',
      'stone',
      'sulphur',
      'truffles',
      'wood',
      'honey',
    ],
  },
  marsh: {
    dice: 'd2',
    resources: [
      'amber',
      'cinnamon',
      'citrus',
      'clay',
      'cloves',
      'cocoa',
      'coffee',
      'crabs',
      'diamonds',
      'ducks',
      'dyes',
      'fish',
      'geese',
      'incense',
      'peacocks',
      'perfume',
      'silk',
      'spices',
      'stone',
      'truffles',
      'wood',
    ],
  },
  'flood-plains': {
    dice: 'd2',
    resources: [
      'clay',
      'cobalt',
      'crabs',
      'deer',
      'diamonds',
      'ducks',
      'fish',
      'geese',
      'horses',
      'truffles',
    ],
  },
  lakes: {
    dice: 'd4',
    resources: [
      'amber',
      'cattle',
      'clay',
      'cobalt',
      'cosmetics',
      'cotton',
      'crabs',
      'deer',
      'ducks',
      'fish',
      'furs',
      'geese',
      'gypsum',
      'horses',
      'iron',
      'marble',
      'perfume',
      'rice',
      'salt',
      'sheep',
      'silk',
      'silver',
      'spices',
      'stone',
      'sulphur',
      'truffles',
      'wheat',
    ],
  },
  oasis: {
    dice: 'd4',
    resources: [
      'aluminum',
      'amber',
      'bananas',
      'bronze',
      'camels',
      'cinnamon',
      'citrus',
      'clay',
      'cloves',
      'coal',
      'cobalt',
      'cocoa',
      'coffee',
      'copper',
      'cosmetics',
      'cotton',
      'crabs',
      'diamonds',
      'dyes',
      'fish',
      'goats',
      'gypsum',
      'incense',
      'iron',
      'ivory',
      'jade',
      'perfume',
      'pigs',
      'spices',
      'truffles',
      'wood',
    ],
  },
};

/** People needed to support one business, and the resources that halve that need. */
export const INDUSTRIES: Record<
  Industry,
  { supportValue: number; advantages: Resource[] }
> = {
  miners: {
    supportValue: 78,
    advantages: [
      'aluminum',
      'amber',
      'bronze',
      'coal',
      'cobalt',
      'copper',
      'diamonds',
      'gold',
      'gypsum',
      'iron',
      'jade',
      'obsidian',
      'salt',
      'stone',
      'sulphur',
    ],
  },
  hunters: {
    supportValue: 54,
    advantages: ['deer', 'geese', 'ducks', 'peacocks', 'ivory'],
  },
  'produce-farmers': {
    supportValue: 24,
    advantages: [
      'bananas',
      'cinnamon',
      'citrus',
      'cloves',
      'cocoa',
      'coffee',
      'cotton',
      'honey',
      'rice',
      'sugar',
      'tea',
      'tobacco',
      'wheat',
    ],
  },
  'horse-farmers': { supportValue: 98, advantages: ['horses'] },
  'cattle-farmers': { supportValue: 34, advantages: ['cattle'] },
  'poultry-farmers': {
    supportValue: 31,
    advantages: ['chickens', 'geese', 'ducks'],
  },
  'pork-farmers': { supportValue: 42, advantages: ['pigs'] },
  goatherders: { supportValue: 54, advantages: ['goats'] },
  shepherders: { supportValue: 47, advantages: ['sheep', 'wool'] },
  butlers: { supportValue: 2000, advantages: [] },
  maidservants: { supportValue: 200, advantages: [] },
  cooks: { supportValue: 200, advantages: [] },
  groundskeepers: { supportValue: 200, advantages: [] },
  carters: { supportValue: 2000, advantages: [] },
  nannies: { supportValue: 400, advantages: [] },
  bodyguards: { supportValue: 200, advantages: [] },
  majordomos: { supportValue: 4000, advantages: [] },
  cobblers: { supportValue: 150, advantages: [] },
  shoemakers: { supportValue: 150, advantages: ['cattle'] },
  furriers: { supportValue: 250, advantages: ['furs'] },
  tailors: { supportValue: 250, advantages: ['cattle', 'furs'] },
  barbers: { supportValue: 350, advantages: ['iron', 'bronze'] },
  jewelers: {
    supportValue: 400,
    advantages: [
      'jade',
      'gold',
      'silver',
      'platinum',
      'gypsum',
      'cobalt',
      'bronze',
      'copper',
      'ivory',
      'pearls',
      'diamonds',
    ],
  },
  taverns: { supportValue: 400, advantages: ['wine', 'wood', 'spices'] },
  clothiers: {
    supportValue: 400,
    advantages: ['wool', 'cattle', 'dyes', 'furs'],
  },
  glassblowers: { supportValue: 400, advantages: [] },
  pastrycooks: { supportValue: 500, advantages: ['chickens', 'wheat'] },
  masons: {
    supportValue: 500,
    advantages: ['clay', 'coal', 'wood', 'gypsum', 'marble', 'stone'],
  },
  carpenters: { supportValue: 550, advantages: ['wood', 'iron', 'bronze'] },
  weavers: {
    supportValue: 600,
    advantages: ['iron', 'wool', 'sheep', 'cotton'],
  },
  chandlers: { supportValue: 700, advantages: ['honey'] },
  mercers: {
    supportValue: 700,
    advantages: ['silk', 'wool', 'cattle', 'cotton'],
  },
  coopers: { supportValue: 700, advantages: ['wood', 'bronze', 'iron'] },
  bakers: {
    supportValue: 800,
    advantages: ['wheat', 'chickens', 'clay', 'wood', 'rice'],
  },
  watercarriers: { supportValue: 850, advantages: ['fish', 'wood', 'springs'] },
  armorers: { supportValue: 950, advantages: [] },
  scabbardmakers: {
    supportValue: 850,
    advantages: ['cattle', 'wood', 'bronze', 'iron', 'copper'],
  },
  'wine-sellers': { supportValue: 800, advantages: ['wine'] },
  tanners: { supportValue: 2000, advantages: ['cattle'] },
  skinners: { supportValue: 1000, advantages: [] },
  leatherworkers: { supportValue: 1000, advantages: [] },
  hatmakers: { supportValue: 950, advantages: ['cattle'] },
  saddlers: { supportValue: 1000, advantages: ['horses'] },
  'chicken-butchers': { supportValue: 800, advantages: ['chickens'] },
  pursemakers: { supportValue: 1100, advantages: ['cattle'] },
  woodsellers: { supportValue: 2400, advantages: ['wood'] },
  'magic-shops': {
    supportValue: 2800,
    advantages: ['dyes', 'sulphur', 'gold', 'perfume', 'incense'],
  },
  bookbinders: { supportValue: 3000, advantages: ['wood', 'cattle'] },
  butchers: {
    supportValue: 800,
    advantages: ['cattle', 'pigs', 'chickens', 'bronze', 'iron'],
  },
  fishmongers: { supportValue: 1200, advantages: ['fish', 'whales', 'crabs'] },
  shipwrights: { supportValue: 2400, advantages: [] },
  'beer-sellers': { supportValue: 1400, advantages: ['wheat'] },
  'buckle-makers': {
    supportValue: 1400,
    advantages: ['bronze', 'copper', 'iron', 'silver', 'gold'],
  },
  plasterers: { supportValue: 1400, advantages: ['clay', 'gypsum'] },
  'spice-merchants': { supportValue: 1400, advantages: ['spices'] },
  blacksmiths: {
    supportValue: 1500,
    advantages: ['bronze', 'copper', 'iron', 'silver', 'gold', 'platinum'],
  },
  painters: { supportValue: 1500, advantages: ['dyes'] },
  roofers: { supportValue: 1800, advantages: ['clay', 'wood', 'marble'] },
  locksmiths: { supportValue: 1900, advantages: ['iron', 'bronze', 'copper'] },
  finesmiths: { supportValue: 2400, advantages: [] },
  bathers: { supportValue: 1900, advantages: ['ivory', 'marble'] },
  potters: { supportValue: 1900, advantages: [] },
  tilemakers: { supportValue: 1900, advantages: [] },
  ropemakers: { supportValue: 1900, advantages: ['wood'] },
  inns: { supportValue: 2000, advantages: ['wood', 'cotton', 'wool'] },
  copyists: { supportValue: 2000, advantages: ['wood', 'gold', 'silver'] },
  sculptors: {
    supportValue: 2000,
    advantages: ['stone', 'marble', 'gold', 'silver'],
  },
  rugmakers: { supportValue: 2000, advantages: ['silk', 'wool', 'furs'] },
  'harness-makers': {
    supportValue: 2000,
    advantages: ['wood', 'bronze', 'iron'],
  },
  bleachers: { supportValue: 2100, advantages: ['dyes'] },
  'hay-merchants': { supportValue: 2300, advantages: ['cattle', 'pigs'] },
  cutlers: { supportValue: 2300, advantages: ['iron', 'silver', 'gold'] },
  glovemakers: { supportValue: 2400, advantages: ['wool', 'cattle'] },
  woodcarvers: { supportValue: 2400, advantages: ['wood', 'iron', 'bronze'] },
  booksellers: {
    supportValue: 6300,
    advantages: ['gold', 'platinum', 'cosmetics'],
  },
  surveyors: { supportValue: 1400, advantages: [] },
  cartographers: { supportValue: 2800, advantages: [] },
  illuminators: { supportValue: 3900, advantages: ['honey', 'wood'] },
  'master-artists': {
    supportValue: 60000,
    advantages: [
      'silver',
      'gold',
      'platinum',
      'dyes',
      'marble',
      'cosmetics',
      'perfume',
    ],
  },
  alchemists: { supportValue: 20000, advantages: [] },
  astronomers: { supportValue: 40000, advantages: [] },
  scribes: { supportValue: 4000, advantages: [] },
  librarians: { supportValue: 6000, advantages: [] },
  scholars: { supportValue: 8000, advantages: ['silver', 'gold', 'platinum'] },
  apprentices: { supportValue: 450, advantages: [] },
  advocates: { supportValue: 650, advantages: ['silver', 'gold', 'platinum'] },
  healers: {
    supportValue: 450,
    advantages: ['incense', 'perfume', 'silver', 'citrus', 'cocoa', 'springs'],
  },
  doctors: {
    supportValue: 1000,
    advantages: ['silver', 'gold', 'iron', 'platinum'],
  },
  clergy: { supportValue: 40, advantages: ['incense', 'gold', 'spices'] },
  priests: { supportValue: 1200, advantages: ['incense', 'gold'] },
  guards: { supportValue: 150, advantages: ['silver', 'gold', 'platinum'] },
};

/** Prosperity as a multiplier on support values: booming needs fewest people per business. */
export const PROSPERITY_FACTOR: Record<Prosperity, number> = {
  booming: 1,
  prosperous: 2,
  poor: 3,
  'very-poor': 4,
};

export const PROSPERITIES: Prosperity[] = [
  'booming',
  'prosperous',
  'poor',
  'very-poor',
];

/** Livestock as a multiple of the population, split by animal. */
export const LIVESTOCK = {
  multiplier: 1.8,
  ratios: {
    chickens: 0.48,
    geese: 0.1,
    ducks: 0.1,
    cattle: 0.08,
    pigs: 0.14,
    sheep: 0.07,
    goats: 0.03,
  },
} as const;

/** Settlement and demesne tiers: population bounds and people per square mile. */
export type SettlementTier =
  | 'hamlet'
  | 'village'
  | 'town'
  | 'city'
  | 'metropolis'
  | 'county'
  | 'duchy'
  | 'kingdom';
export const TIERS: Record<
  SettlementTier,
  {
    min: number;
    max: number;
    density: number;
    scale: 'locality' | 'county' | 'duchy' | 'kingdom';
  }
> = {
  hamlet: { min: 20, max: 150, density: 2560, scale: 'locality' },
  village: { min: 150, max: 800, density: 6400, scale: 'locality' },
  town: { min: 800, max: 8000, density: 15360, scale: 'locality' },
  city: { min: 8000, max: 20000, density: 30720, scale: 'locality' },
  metropolis: { min: 20000, max: 120000, density: 61440, scale: 'locality' },
  county: { min: 500, max: 300000, density: 75, scale: 'county' },
  duchy: { min: 20000, max: 3000000, density: 75, scale: 'duchy' },
  kingdom: { min: 100000, max: 8000000, density: 75, scale: 'kingdom' },
};

export const LOCALITY_TIERS: SettlementTier[] = [
  'hamlet',
  'village',
  'town',
  'city',
  'metropolis',
];

/** Square miles per scale, and 640 acres to the square mile. */
export const SCALE_SQUARE_MILES = {
  locality: 1,
  county: 800,
  duchy: 16000,
  kingdom: 80000,
} as const;
export const ACRES_PER_SQUARE_MILE = 640;
